version: '3.8'

services:
  db:
    container_name: auth_db
    image: postgres:18
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - db_auth_network

  auth-app:
    container_name: auth_app
    build: .
    restart: always
    environment:
      DB_ENGINE: postgresql
      DB_NAME: authdb
      DB_USERNAME: authuser
      DB_PASS: authpass
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    networks:
      - db_auth_network
      - web_auth_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5006:5085"

  auth-nginx:
    container_name: auth_nginx
    image: nginx:latest
    restart: always
    # ports:
    #   - "5005:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_auth_network
    depends_on:
      - auth-app

networks:
  db_auth_network:
    driver: bridge
  web_auth_network:
    driver: bridge

volumes:
  db_data:
